### PR TITLE
Bump grpc-gateway version

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Bump grpc-gateway to https://github.com/grpc-ecosystem/grpc-gateway/pull/497 for https://github.com/cockroachdb/cockroach/pull/20983.

Also includes https://github.com/cockroachdb/vendored/commit/ca29dc9048bee1542ac140a93999cd87d6a902f7.

### CODE REVIEW

**Comment by benesch** [comment]
This is pushed to origin as branch `johanbrandhorst/bump-grpc-gateway`.

**Comment by johanbrandhorst** [comment]
Yes.. is that incorrect? I read through the instructions on https://github.com/cockroachdb/cockroach/blob/master/build/README.md#dependencies, was I not supposed to do it like this?

**Comment by benesch** [comment]
No, you did it exactly right! Unfortunately the instructions are a little bit out of date. I'll merge this PR after your cockroachdb/cockroach PR lands; in the meantime, the existence of the equivalent origin branch means CI will be able to find those commits when you bump the submodule ref in your cockroachdb/cockroach PR.

**Comment by johanbrandhorst** [comment]
I've force pushed to my branch so I think the local copy will need to be updated :(

**Comment by johanbrandhorst** [comment]
Apparently this may not need to be rebased after all, as long as we merge this into master at some point? Submodules confuse me.

**Comment by benesch** [comment]
Sorry for confusing you by creating a branch! Glad we got this merged.

**Pull request merged**
