### PR TITLE
Bump stress - for real

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by tamird** [comment]
(no need for the PR, right?)

**Comment by knz** [comment]
hmm ok I didn't know we could merge those to master directly.

**Comment by tamird** [comment]
We usually push a branch containing the new ref, then send a PR to the main repo, and then fast-forward master to the new ref.

**Comment by knz** [comment]
Oh I didn't know this. Thanks for explaining.

**Comment by tschottdorf** [comment]
Either I'm missing something, or this was going back in time -- https://github.com/cockroachdb/cockroach/pull/18687#issuecomment-331296669

**Comment by knz** [comment]
`dep` in the cockroach master branch is producing this diff.

**Pull request merged**
