### PR TITLE
Remove go-bindata-assetfs

### PR DESCRIPTION
**Pull request by koorosh**
related to https://github.com/cockroachdb/cockroach/pull/69135

### CODE REVIEW

**Comment by koorosh** [comment]
note, this pr includes extra commits (from branches that weren't merged into master branch).

**Comment by koorosh** [comment]
hi @knz ,  I (as external contributor) try to follow this doc [Working with Submodules](https://github.com/cockroachdb/cockroach/blob/master/build/README.md#working-with-submodules) and found some inconsistency in documentation, it's not clear whether such PRs from forked repositories should be created against `master` branch or not because as mentioned in doc: 
>> Since the cockroachdb/cockroach submodule references individual commit hashes in vendored, there is little significance to the master branch in vendored -- as outlined above, new commits are always authored with the previously referenced commit as their parent, regardless of what master happens to be.

- would it be okay to merge this PR with extra commits and then reference to `master` branch in `cockroachdb/cockroach` repo?

Appreciate any help to clarify what is a proper way to contribute to this repository as a non-member.
Thanks!

**Comment by knz** [comment]
You do not need to merge a PR here to use the SHA in the crdb repo.

Just keep it here and go ahead with the crdb PR on the other side

**Comment by koorosh** [comment]
Ah, I see, thank you for help!

**Pull request merged**
