### PR TITLE
bump golang.org/x/crypto/ssh and its deps

### PR DESCRIPTION
**Pull request by alan-mas**
As we are removing support for spinning up cassandra clusters, we need to refresh/rebuild vendor deps
so we are taking away `ssh` and its deps like:
- golang.org/x/crypto/chacha20
- golang.org/x/crypto/curve25519
- golang.org/x/crypto/internal/subtle
- golang.org/x/crypto/poly1305
- golang.org/x/crypto/ssh/agent
- golang.org/x/crypto/ssh/internal/bcrypt_pbkdf
- golang.org/x/crypto/ssh/knownhosts
- golang.org/x/sys/cpu

### CODE REVIEW

**Comment by knz** [comment]
we don't usually create Prs in this repository.
The process is to create the branch but organize the PR on the main crdb repo.

**Comment by alan-mas** [comment]
> we don't usually create Prs in this repository.
> The process is to create the branch but organize the PR on the main crdb repo.

Thanks for your reply @knz !
I have no access to create a branch in here or even to assign people to this PR, that is why I was like "following" the same steps as I did in the `protobuf` submodule.

This issue is related to this [Pull request](https://github.com/cockroachdb/cockroach/pull/64029) as it is failing at CI :(

Is there any docs or process I could follow to solve this?

**Comment by knz** [comment]
Yes you can ask someone (like me) to push your branch to the vendored repo. I will do this now for you.

**Comment by knz** [comment]
Done https://github.com/cockroachdb/vendored/tree/bump-ssh

You can now use the sha 17d1c1fc076405f1135f223e02de9bb0ff81eadd  in your PR at #64029

**Comment by alan-mas** [comment]
Hey @knz 
Not sure what happened, but my code at CI failed, so I re-run `make -k vendor_rebuild` at my local branch (`bump-ssh`) and new changes appeared so I updated this PR as well.

But I am not totally sure if this could be happening in the future (like I need to run `make -k vendor_rebuild` in next few days or something) What do you think is the best strategy on this? 

I am pretty sure there is something I am missing in here.

**Comment by knz** [comment]
what happened is that someone else updated the vendored dep "under" your PR. So you can't use your SHA any more and need to re-construct a new one from the one in the crdb repo.

**Comment by alan-mas** [comment]
@knz do you think can you help me on re-construct a new branch with the new SHA? `aa8a53a3ca360884640d2dd667e781e478d72c97` but in case you are much busy I can ask someone else from Infra team to help me =)

Thank you so much for your help on this!

**Comment by knz** [comment]
i can help you with that but if you ask me it will need to wait tomorrow.
What I don't understand however is why we've made this work so complicated for you. That's really an artificial problem that we've created. @jlinder could you perhaps provide some suggestions as to how to smoothen this experience for Alan in thefuture?

**Comment by knz** [comment]
ok I fixed up your branch here and I think the original PR is fine now.
However I force-pushed to your github repo, and you'll need to update your local copy from github before you can go further.

**Comment by alan-mas** [comment]
@knz you totally rocks, thank you so much!

Let me do that and keep checking this :)

**Comment by jlinder** [comment]
> @jlinder could you perhaps provide some suggestions as to how to smoothen this experience for Alan in the future?

Yes. I'm currently working on getting Alan improved access that would remove these hurdles.

**Comment by knz** [comment]
I think we can close this PR now.

**Pull request closed without merging**
