### PR TITLE
Bump etcd.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by tamird** [comment]
FYI we haven't been doing PRs in this repo to avoid merge commits. The
procedure has been to push the updated SHA to master after merging PRs in
the main repo.

3 янв. 2017 г. 11:19 пользователь "Peter Mattis" <notifications@github.com>
написал:

**Comment by petermattis** [comment]
What am I doing wrong:

```
git push -f origin master
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to a protected branch
To ssh://git@github.com/cockroachdb/vendored
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'ssh://git@github.com/cockroachdb/vendored'
```

**Comment by dt** [comment]
it only accepts fast-forwards (i.e. rebase it).

thread hijack: we don't *really* care what master points to in this repo so much as that every referenced commit from main repo is protected from being GC'ed. maybe we should just have a post-merge hook on main repo that tags new submodule refs with the PR number or something, and then we can kill branch protection on master.

**Comment by petermattis** [comment]
Ah, I see. I should have pushed. Force pushing won't work.

**Comment by bdarnell** [comment]
I think using (and protecting) `master` in this repo is still useful - if we just tag non-master commits when they're referenced in the main repo, what protects us from updating the submodule to point to a commit that's not an ancestor of the previous version?

**Comment by dt** [comment]
since the `vendor` dir is just a materialization of the lock file which lives in (and thus has history linearized in) the main repo, do we actually care much about ancestry of commits in the vendor repo? seems like it could pretty much just be treated as unordered ref storage.

**Comment by bdarnell** [comment]
For example, cockroachdb/cockroach#12631 changed the submodule pointer from adf3d69d to 1e262056, but there's no guarantee that the former is an ancestor of the latter, so commits that made it into master in the main repo could get lost accidentally. If we made a habit of tracking the main repo's submodule in this repo's `master` branch, then the branch protection would let us know that this had happened. Maybe that's not something worth worrying about, though, since all the other version checks in glide.lock wouldn't match up if we did something wrong here.

**Pull request merged**
