### PR TITLE
add github.com/shirou/gopsutil net and disk packages

### PR DESCRIPTION
**Pull request by vilterp**
This library gathers disk and network IO stats from the host kernel, which we'll record to the TS system.

### CODE REVIEW

**Comment by vilterp** [comment]
@benesch looks like your commit to add `cgosymbolizer` didn't make it onto master?

**Comment by benesch** [comment]
Whoops, thanks. Fixed now.

**Comment by benesch** [comment]
P.S. don't worry about PRs in this repo. Just push to an origin branch.

**Comment by benesch** [comment]
GitHub is confused and displaying the wrong diff. Closing and reopening to see if that fixes it.

**Comment by vilterp** [comment]
Closing in favor of #23… third time's the charm

**Pull request merged**
