### PR TITLE
upgrade grpc to v1.47.0

### PR DESCRIPTION
**Pull request by pavelkalinnikov**

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
No need to merge to `master`, the branch stays in this repo, and the corresponding commit will be referenced.

**Comment by pavelkalinnikov** [comment]
Will create a new branch, because it's very tempting to press "Delete branch" in this PR at any time in the future.

**Comment by pavelkalinnikov** [comment]
> we typically fast forward push master to the referenced commit after the cockroachdb/cockroach PR referencing it merges at which point it is permanently going to be reachable from a protected branch; at that point you can delete the named branch

@dt What if `crdb` master rolls back to reference the previous commit of `vendored`? And then, say, upgrades to a different version. In this case we can't fast-forward `vendored` master, will have to move it to the forked branch, and leave a placeholder branch in the old master instead.

Does it never happen?

**Comment by dt** [comment]
vendored/master is protected, so if someone made a new vendored commit off of an older parent than the current head, you'd need a merge commit to push it

**Comment by dt** [comment]
perfect -- in the meantime it looks like nobody has pushed the _currently_ crdb referenced commit to master here for awhile (meaning it isn't protected) so I'll do that real quick.

**Comment by pavelkalinnikov** [comment]
@dt thanks. I will rebase after you do it, this PR will nicely contain one commit then.

**Pull request merged**
