### PR TITLE
pq: add `ColumnTypeScanType()` implementation

### PR DESCRIPTION
**Pull request by pkit**
`ColumnTypeScanType()` can be used to get runtime information about column types

### CODE REVIEW

**Comment by knz** [comment]
@andreimatei this is the patch that will fix your issue https://github.com/cockroachdb/cockroach/issues/10042

**Comment by pkit** [comment]
This one looks like standard interface, supported on `driver.sql` level
Less code changes, more supported functions...

**Comment by mjibson** [comment]
There's already a PR for this at https://github.com/lib/pq/pull/647

Also, this repo only supports updating with dep. We don't add arbitrary code like this, because it'll get removed by the next dep update.

**Comment by knz** [comment]
@mjibson thanks for merging that other PR.
 @pkit can you move forward with that?

**Comment by pkit** [comment]
@knz what's the correct way of updating vendored stuff after that upstream update?
I think it should work either way, but just to make it tidy and clean.

**Comment by knz** [comment]
Using the `dep ensure` command with just the pq dependency. I think there's a reference to it in build/README.md. Otherwise perhaps ask help from @benesch .

**Comment by benesch** [comment]
Yeah, checkout cockroachdb/cockroach and follow the instructions in build/README.md.

**Pull request closed without merging**
